### PR TITLE
[WIP] Refactoring to use React.Children.count from array-based length

### PR DESCRIPTION
**Pull request by 1Copenut**
## Description
The original Formation Breadcrumb component used an array-based approach to count children. If individual items were passed to the component as children, it threw an error. Refactored it to use `React.Children`count` as outlined in the article [A deep dive into children in React](https://mxstbr.blog/2017/02/react-children-deepdive/#counting-children).

I'm open to further refactoring as needed. I've tagged this **WIP** for that reason.

## Testing Done
* Pulled the feature branch into `vets-website` locally using `yalc link`
* Did manual testing of public, logged in breadcrumb implementations
* Ran unit, e2e suites of tests

## Original Issue Ticket
* https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11842

### CODE REVIEW

**Comment by 1Copenut** [comment]
@rianfowler @erikphansen I refactored the `renderBreadcrumbs()` method per the discussion here, and wanted to ask for a quick review before I merge and cut a new release.

I ran the update through the vets-website test suite using yalc, all passed. I think we can call this a `MINOR` since it doesn't appear to be a breaking change.

**Comment by rianfowler** [comment]
LGTM - does it work?

**Comment by 1Copenut** [comment]
@rianfowler It works as much as I can observe:

1. Test suites pass for design-system unit tests, vets-website e2e tests
2. Observed the breadcrumb updating in e2e tests and manual testing
3. Tried it out with GIBCT and Facility Locator, where I knew the breadcrumb would be updating based on app logic

Any other tests to try? I'm working on a few things today and tomorrow, so will look to cut a new release and pull into vets-website Monday for a Tuesday release.

**Comment by jbalboni** [comment]
@1Copenut Is this still valid?

**Comment by 1Copenut** [comment]
@jbalboni Yes, I've just not had a good window to merge it. I like to allow a couple of days where I'm not working on big audits, in case something breaks that the tests didn't pick up. I can merge this and cut a new design system release later today, and probably get a PR for `vets-website` tomorrow or Friday. Otherwise, will target Monday to get both done.

**Comment by jbalboni** [comment]
Ok, cool. Getting it merged today would be great. I'd like to transfer this repo over to another one and I'm hoping I can get all relevant PRs merged and freeze changes for a few hours today.

**Pull request merged**
