### PR TITLE
adding LoadingIndicator

### PR DESCRIPTION
**Pull request by annekainicUSDS**

### CODE REVIEW

**Comment by phiden** [comment]
Thanks @annekainicUSDS for doing the bulk of the work -- this one's ready for review

**Comment by jbalboni** [comment]
@phiden @annekainicUSDS Something seems to have gone awry, there are a lot of changes in this PR.

**Comment by phiden** [comment]
@jbalboni Yeah, my fault -- there were conflicts so I brought master in to try to resolve them :/ Suggestions for how to proceed? Could open a new branch and go from there?

**Comment by jbalboni** [comment]
@phiden A new branch is probably easiest.

**Pull request closed without merging**
